# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Hydro-Informatics
author: Sebastian Schwindt
copyright: "2021"  # Copyright year to be placed in the footer
logo: img/icons/icon.jpg
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files: true

################################################################################
# Execution settings
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache: ""    # A path to the jupyter cache that will be used to store execution artifacts. Defaults to `_build/.jupyter_cache/`
  exclude_patterns: []    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout: 30    # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp: false # If `True`, then a temporary directory will be created and used as the command working directory (cwd) otherwise the notebook's parent directory will be the cwd.
  allow_errors: true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output: show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

#################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

  myst_url_schemes: [mailto, http, https]  # URI schemes that will be recognised as external URLs in Markdown links
  myst_substitutions:
    ft_env: "[flussenv environment.yml](https://raw.githubusercontent.com/Ecohydraulics/flusstools-pckg/main/environment.yml)"
    ft_req: "[flusstools requirements.txt](https://raw.githubusercontent.com/Ecohydraulics/flusstools-pckg/main/requirements.txt)"
    ft_url: "[flusstools](https://flusstools.readthedocs.io)"
    getpy: "[Python](https://www.python.org/downloads/)"
    uni_portal: "[the University of Stuttgart's ILIAS platform](https://ilias3.uni-stuttgart.de)"


################################################################################
# LaTeX-specific settings
latex:
  latex_engine: pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex: true # use jupyterbook-latex for pdf builds as default
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib
bibtex_reference_style: author_year  # or label, super, \supercite

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface: jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: https://mybinder.org/v2/gh/hydro-informatics/hydro-informatics.github.io/main?filepath=jupyter  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url: ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe: true  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url: https://colab.research.google.com/ # The URL of Google Colab (https://colab.research.google.com)

# Information about where the book exists on the web
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
repository:
  url: https://github.com/hydro-informatics/hydro-informatics.github.io  # Online location of your book
  path_to_book: _sources  # Optional path to your book, relative to the repository root
  branch: gh-pages  # Which branch of the repository should be used when creating links (optional)

#################################################################################
html:
  favicon: "img/icons/favicon.ico"  # A path to a favicon image
  use_edit_page_button: false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button: true  # Whether to add a link to your repository button
  use_issues_button: false  # Whether to add an "open an issue" button
  extra_navbar: Written by <a href="https://sebastian-schwindt.org">Sebastian Schwindt</a>  # Will be displayed underneath the left navbar.
  extra_footer: ""  # Will be displayed underneath the footer.
  google_analytics_id: ""  # A GA id that can be used to track book views.
  home_page_in_navbar: false  # Whether to include your home page in the left Navigation Bar
  baseurl: "https://hydro-informatics.github.io"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis: false
    utterances: false

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions:
    - sphinx_click.ext
    - sphinx_inline_tabs
    - sphinx_sitemap
  local_extensions:   # A list of local extensions to load by sphinx specified by "name: path" items
  config:
    mathjax_config:
      TeX:
        Macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat" : ["\\left[\\begin{array}"]
          "emat" : ["\\end{array}\\right]"]
