name: hywin
channels:
  - default
  - conda-forge
  - eoas_ubc
dependencies:
  - python=3.7.*
  - sphinx=2.4.4
  - pip
  - runjb
  - git
  - pandas
  - matplotlib
  - pip:
    - quantecon
    - ghp-import
    - jupyter-book>=0.7.0b
    - sphinx-click
    - sphinx_inline_tabs
